### ISSUE TITLE
Simulation question

### ISSUE THREAD

**Issue by hello-eternity** [rolandbernard/kleine-riscv#4]
When I directly run the `make` command after git this repo, here I got an error 
```
make[1]: Entering directory '/work/kleine-riscv/tests'
Building build/misc/ackermann
clang-10: warning: argument unused during compilation: '-fuse-ld=lld' [-Wunused-command-line-argument]
error: unable to create target: 'No available targets are compatible with triple "riscv32-unknown-unknown"'
1 error generated.
make[1]: *** [makefile:35: build/misc/ackermann] Error 1
make[1]: Leaving directory '/work/kleine-riscv/tests'
make: *** [makefile:46: tests/build] Error 2
```
Do you have any suggestion to solve this?

`make sim` can run correctly.

**Comment by hello-eternity** [comment]
Make sense, Thank you

**Comment by rolandbernard** [comment]
From the error message, I assume that your build of clang does not support the riscv target. (You can check the targets it was build for with `llc --version` or `llvm-config --targets-built`)
In any case, if you want to use the Makefile as is, you need both clang and lld with support for riscv32 targets. If you have a gcc toolchain for riscv32 installed, you could also change in the file `tests/makefile` the variable `CC` to the gcc binary (something like `riscv32-elf-gcc` probably) and remove the `-fuse-ld=lld` option from `CFLAGS`.

**Comment by hello-eternity** [comment]
That worked, thank you very much!
